version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo Installing custom PHP version 8.1.12...
      - phpenv install 8.1.12
      - phpenv global 8.1.12
  build:
    commands:
      - echo Build started on `date`
      - composer install
      - php artisan config:cache
      - php artisan migrate --force
artifacts:
  files:
    - '**/*'
  discard-paths: yes
